# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8084:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: jim
      MYSQL_DATABASE: myDatabase
      MYSQL_USER: myUsername
      MYSQL_PASSWORD: myPassword
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
